const $=id=>document.getElementById(id),state={file:null,detections:[]};
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>show(b.dataset.page));
function show(p){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===p));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===p));document.querySelector("nav").classList.remove("open");scrollTo({top:0,behavior:"smooth"})}
$("menu").onclick=()=>document.querySelector("nav").classList.toggle("open");
$("browse").onclick=()=>$("file").click();
$("drop").onclick=e=>{if(e.target.id==="drop"||e.target.tagName==="H3"||e.target.tagName==="P")$("file").click()};
$("file").onchange=()=>{if($("file").files[0])setFile($("file").files[0])};
$("drop").ondragover=e=>{e.preventDefault();$("drop").style.borderColor="#2e7d32"};
$("drop").ondrop=e=>{e.preventDefault();$("drop").style.borderColor="";if(e.dataTransfer.files[0])setFile(e.dataTransfer.files[0])};
function setFile(f){$("error").classList.add("hidden");if(!["image/jpeg","image/png","image/webp"].includes(f.type))return err("Unsupported image format.");state.file=f;$("preview").src=URL.createObjectURL(f);$("name").textContent=f.name;$("drop").classList.add("hidden");$("previewWrap").classList.remove("hidden");$("results").classList.add("hidden")}
function err(x){$("error").textContent=x;$("error").classList.remove("hidden")}
$("remove").onclick=()=>{state.file=null;$("file").value="";$("previewWrap").classList.add("hidden");$("drop").classList.remove("hidden");$("results").classList.add("hidden")};
$("analyze").onclick=async()=>{if(!state.file)return err("Select an image first.");$("loading").classList.remove("hidden");$("analyze").disabled=true;try{const fd=new FormData();fd.append("file",state.file);const r=await fetch("/api/predict",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw Error(d.detail||"Prediction failed");state.detections=d.detections;render(d)}catch(e){err(e.message)}finally{$("loading").classList.add("hidden");$("analyze").disabled=false}};
function render(d){$("results").classList.remove("hidden");$("total").textContent=d.total_detections;$("land").textContent=d.summary.land_animals;$("sea").textContent=d.summary.sea_animals;$("birds").textContent=d.summary.birds;$("avg").textContent=d.summary.average_confidence+"%";$("time").textContent=d.processing_time_ms+" ms";$("model").textContent=d.model_name;$("resultImg").src=d.annotated_image_url+"?t="+Date.now();drawList()}
function drawList(){const q=$("search").value.toLowerCase(),c=$("cat").value,m=Number($("min").value);const a=state.detections.filter(x=>x.class_name.toLowerCase().includes(q)&&(c==="All"||x.category===c)&&x.confidence_percent>=m);$("list").innerHTML=a.length?a.map(x=>{const b=x.bbox;return `<div class="item"><div class="itemTop"><div><b>${x.class_name}</b><small>${x.category} · ${x.status}</small></div><b>${x.confidence_percent}%</b></div><div class="prog"><span style="width:${Math.min(100,x.confidence_percent)}%"></span></div><div class="bbox">Box: [${b.x1}, ${b.y1}] → [${b.x2}, ${b.y2}]</div></div>`}).join(""):'<div class="card" style="box-shadow:none;text-align:center">No detections match the filters.</div>'}
["search","cat","min"].forEach(id=>$(id).oninput=drawList);
async function load(){try{const h=await (await fetch("/api/health")).json();$("health").textContent=h.model_loaded?"Model ready · "+h.model:"Model not loaded";$("health").style.color=h.model_loaded?"#2e7d32":"#b3261e";const c=await (await fetch("/api/classes")).json();$("coverage").textContent=c.model_loaded?"Loaded model exposes "+c.actual_model_classes.length+" classes.":"No model loaded. Configure MODEL_PATH and add weights.";const intended={land:["Dog","Cat","Lion","Tiger","Leopard","Cheetah","Elephant","Horse","Cow","Buffalo","Goat","Sheep","Deer","Monkey","Gorilla","Bear","Panda","Wolf","Fox","Rabbit","Zebra","Giraffe","Camel","Kangaroo","Hippopotamus","Rhinoceros","Pig","Donkey","Squirrel","Rat","Mouse"],sea:["Shark","Dolphin","Whale","Orca","Seal","Sea Lion","Walrus","Octopus","Squid","Jellyfish","Starfish","Seahorse","Crab","Lobster","Shrimp","Turtle","Sea Turtle","Stingray","Eel","Swordfish","Tuna","Salmon","Clownfish","Goldfish","Pufferfish","Angelfish","Manta Ray"],bird:["Eagle","Sparrow","Crow","Parrot","Peacock","Pigeon","Owl","Hawk","Falcon","Swan","Duck","Goose","Flamingo","Penguin","Ostrich","Emu","Kingfisher","Woodpecker","Hummingbird","Parakeet","Pelican","Seagull","Crane","Heron","Rooster","Hen","Turkey"]};const set=new Set(c.actual_model_classes.map(x=>x.toLowerCase()));for(const [k,a] of Object.entries(intended))$(k+"Classes").innerHTML=a.map(n=>`<div class="chip"><b>${n}</b><small>${set.has(n.toLowerCase())?"✓ Supported":"○ Training required"}</small></div>`).join("")}catch{}}
load();